module.exports = {
  appstore_link: "empty",
  playstore_link: "empty",
  google_analytics_ID: "",
  presskit_download_link: "",
  video_or_screenshot: "video",
  app_url: "http://au-designs.com",
  path_prefix: "/",
  app_name: "ARulity",
  app_price: "Free",
  app_description:
    "Turn your device into measuring tool using Augmented Reality (AR) technology. You can accurately determine the sizes of objects using this technology. Measuring from Point A to Point B",
  app_keywords: [
    "automatic",
    "gatsbyjs",
    "app",
    "landing page",
    "AR",
    "measure",
    "Ios",
  ],

  your_name: "Carlos Felix-Beltran",
  your_link: "http;//www.au-designs.com",
  your_city: null,
  email_address: null,
  facebook_username: "UA-Designs",
  instagram_username: "UA-Designs",
  twitter_username: "UA-Designs",
  github_username: null,
  youtube_username: null,

  features: [
    {
      title: "Single Measurement",
      description:
        "ARulity technology allows users to select 2 points on the multi touch devices and retrieve accurate data measurement. Simply Magic!",
      fontawesome_icon_name: "magic",
      title2: "Multiple Metrics Support",
      description2:
        "Preview the data in multiple measuring metrics such as Inches & Centimeters. ",
      fontawesome_icon_name2: "mobile",
    },
  ],
  header_background: "#fff",
  topbar_title_color: "#ffffff",
  cover_overlay_color_rgba: "rgba(54, 59, 61, 0.8)",
  device_color: "white",
  body_background_color: "#ffffff",
  primary_text_color: "#000",
  content_width: "1170px",
  font: `"Helvetica Neue", sans-serif`,
  app_title_color: "#ffffff",
  app_price_color: "#ffffff",
  app_description_color: "#ffffff",
  feature_title_color: "#000000",
  feature_text_color: "#666666",
  feature_icons_foreground_color: "#1d63ea",
  feature_icons_background_color: "#e6e6e6",
  social_icons_foreground_color: "#666666",
  social_icons_background_color: "#e6e6e6",
  footer_text_color: "#666666",
  theme: "light", //light or dark
}
